In [1]:
import tensorflow as tf
import numpy as np

M = tf.Variable(tf.eye(4, batch_shape=[1]), dtype=tf.float32)
M5 = tf.Variable(5*tf.eye(4, batch_shape=[1]), dtype=tf.float32)

# loss = tf.nn.l2_loss(M - M_gt)
# optimizer = tf.train.AdamOptimizer(0.001)
# train_op = optimizer.minimize(loss)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
# sess.run(train_op)
print('--------------------')
print(M.eval(sess))
print(M5.eval(sess))
print('--------------------')

uu = tf.assign(M, 2*M5)
sess.run(uu)

print('--------------------')
print(M.eval(sess))
print(M5.eval(sess))
print('--------------------')


--------------------
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]
[[[5. 0. 0. 0.]
  [0. 5. 0. 0.]
  [0. 0. 5. 0.]
  [0. 0. 0. 5.]]]
--------------------
--------------------
[[[10.  0.  0.  0.]
  [ 0. 10.  0.  0.]
  [ 0.  0. 10.  0.]
  [ 0.  0.  0. 10.]]]
[[[5. 0. 0. 0.]
  [0. 5. 0. 0.]
  [0. 0. 5. 0.]
  [0. 0. 0. 5.]]]
--------------------


In [6]:
np.shape(M5)[1].value

4